### ISSUE TITLE
Class 'Kanboard\Formatter\TaskGanttFormatter' not found

### ISSUE THREAD

**Issue by Busfreak** [oliviermaridat/kanboard-milestone-plugin#10]
Hi!
The plugin needs to be updated for KB 1.0.42.
The Gantt chart has been mooved to a plugin, so there is a need for checking dependencies and with plugin Gantt installed it throws error:
Fatal error: Class 'Kanboard\Formatter\TaskGanttFormatter' not found in /.xx./plugins/Milestone/Formatter/TaskGanttLinkAwareFormatter.php on line 14

**Comment by liaoqinghai** [comment]
Same error

include("../../../Gantt/Formatter/TaskGanttFormatter.php");
use Kanboard\Plugin\Gantt\Formatter\TaskGanttFormatter;

**Comment by fguillot** [comment]
Proposed PR #11 and PR #12
