### ISSUE TITLE
incompatible plugin with kanboard 1.44

### ISSUE THREAD

**Issue by donat1** [oliviermaridat/kanboard-milestone-plugin#13]
The milestone plugin is stated as incompatible. What is wrong with our installation?

We have following installation:
Kanban Version: 1.0.44
PHP Version: 5.6.30-1~dotdeb+7.1
PHP SAPI: apache2handler
OS Version: Linux 3.2.0-4-amd64
Datenbanktreiber: postgres
Datenbank Version: 9.5.6

**Comment by dharmann** [comment]
I've updated my instance to 1.0.45. As obvious, Milestone is incompatible with this version too...

**Comment by oliviermaridat** [comment]
This is now fixed! I misunderstood getCompatibleVersion function.

Thank you for your help! I sent a PR, the new version should be available soon.
