### ISSUE TITLE
Cannot see kanboard-milstone-plugin in plugin manager

### ISSUE THREAD

**Issue by szawadski** [oliviermaridat/kanboard-milestone-plugin#5]
Hello,
I cannot see the milstone plugin in the Kanboard plugins manager.
My Kanboard version is: 1.0.32
Has it been tested with 1.0.32?

Regards,

Sébastien

**Comment by oliviermaridat** [comment]
Not yet. I will do it soon.

**Comment by oliviermaridat** [comment]
It is now tested and updated. A PR is in progress to update the plugin repository.
