### ISSUE TITLE
milestone progress indicator is not useful

### ISSUE THREAD

**Issue by poVoq** [oliviermaridat/kanboard-milestone-plugin#8]
Shouldn't the progress indicator be somehow calculated from the depending tasks?

**Comment by oliviermaridat** [comment]
Thank you for this suggestion! Actually, progress indicator was using depending tasks "estimated / real time tracking". I have now added another progress indicator using the depending tasks columns.

Note that this will not work perfectly for tasks from other projects with a different number of columns.
