### ISSUE TITLE
trouble with deleting files if your plugin is active

### ISSUE THREAD

**Issue by thob** [oliviermaridat/kanboard-milestone-plugin#9]
Please check https://github.com/kanboard/kanboard/issues/3088

**Comment by oliviermaridat** [comment]
Thanks. I will check that soon. Can you check that you already have the last version of the Milestone plugin please?

**Comment by thob** [comment]
1.0.38-1?

**Comment by oliviermaridat** [comment]
I tested with the last version (upload and delete a file to a milestone or a non-milestone task) and I do not manage to reproduce the issue. Can you update and check again please? Thanks!
